config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  resources :goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :life_goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'


resources :admin

end

app/views/shared/_header.html.erb
<% if logged_in? %>
  <div id="app-header" class="section">
    <div class="level">
      <div class="level-left">
        <div id="menu-expand-button" class="is-hidden" onclick="menu_expand('side-menu')">
          <%= embedded_svg("menu.svg", class:"menu-svg") %>
        </div>        
          <% url = request.path_info %>
          <% if url == "/goals" %>
            <div class="level-item">
              <h2 class="title page-title"><%= @horizon.capitalize+"ly" %> Goals</h2>
            </div>
            <div class="level-item">
              <%= link_to "New Goal", new_goal_path(horizon: @horizon), remote: true, class: "button is-primary modal-button" %>
            </div>
          <% elsif url == "/life_goals" %>
            <div class="level-item">
              <h2 class="title page-title">Life Goals</h2>
            </div>
            <div class="level-item">
              <%= link_to "New Goal", new_life_goal_path, remote: true, class: "button is-primary modal-button" %>
            </div>
          <% elsif url == "/goals/edit_multiple" %>
            <div class="level-item">
              <h2 class="title">Update <%= @horizon.capitalize+"ly" %> Goals</h2>
            </div>
          <% elsif url == "/life_goals/edit_multiple" %>
            <div class="level-item">
              <h2 class="title">Update Life Goals</h2>
            </div>
          <% elsif url == "/admin" %>
            <div class="level-item">
              <h2 class="title">Admin Dashboard</h2>
            </div>
          <% else %>
            <div class="level-item">
              <div class="title">My Goal App</div>
            </div>
            <div class="level-item">
              <%= link_to "New Goal", new_goal_path(horizon: "week"), remote: true, class: "button is-primary modal-button" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_modal_goal_edit.html.erb
<% @term = params[:term] %>
<%= form_with model: @goal, url: goal_path(@goal, horizon: @horizon), local: true, data:{remote: true} do |f| %>
  
  <div class="field"> 
    <p class="heading">Title</p>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
    <p id="title-error" class="help is-danger"><%= @goal.errors[:title].first %></p>
  </div>

  <div class="field">
    <p class="heading">Description</p>
    <div class="control">
      <%= f.text_area :description, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <p class="heading">Parent Goal</p>
    <div class="control"> 
      <div class="select">
        <%= f.select :parent_goal_id, options_from_collection_for_select(@parent_goals, 'id', 'title', @goal.parent_goal_id), include_blank: true %>
      </div>
    </div>
  </div>

  <div class="field">
    <p class="heading">Due Date</p>
    <div class="control">
      <%= f.radio_button :date, DateTime.current.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'),
      :checked => !!(@goal.this_term?(@horizon)), id: "radio-thisterm-#{@goal.id}", class: "is-checkradio", onclick: "customeDate(#{@goal.id})" %>
      <label for="radio-thisterm-<%= @goal.id %>">
        This <%= @horizon %>
      </label>
      <%= f.radio_button :date, next_term(@horizon).from_now.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'),
      :checked => !!(@goal.next_term?(@horizon)), id: "radio-nextterm-#{@goal.id}", class: "is-checkradio", onclick: "customeDate(#{@goal.id})" %>
      <label for="radio-nextterm-<%= @goal.id %>">
        Next <%= @horizon %>
      </label>
      <%= f.radio_button :date, "", :checked => !(!!(@goal.this_term?(@horizon)) || !!(@goal.next_term?(@horizon))), id: "radio-customterm-#{@goal.id}", class: "is-checkradio", onclick: "customeDate(#{@goal.id})" %>
      <label for="radio-customterm-<%= @goal.id %>">
        Custom
      </label>
      <%= f.date_field :date, value: @goal.date,id: "date-picker-#{@goal.id}", class: (params[:term]=='term_previous' ? "" : "is-hidden") %>
    </div>
    <p><%= @goal.errors[:date].first %></p>
  </div>

  <div class="field">
    <p class="heading">Achievement</p>
    <div class="control">
      <div class="select">
        <%= f.select :achievement, options_for_select({"Achieved" => "achieved", "Partially achieved" => "partially achieved", "Failed" => "failed"}, @goal.achievement), include_blank: true %>
      </div>
    </div>
  </div>

  <!-- this submit button is triggered from the button in the _modal_goal_edit_save partial -->
  <p class="is-hidden"><%= f.submit "Update", id: "edit-form-update" %></p>

<% end %>

<%= link_to goal_path(@goal, horizon: @horizon, term: params[:term]), method: :delete, data: { confirm: "Delete Goal: #{@goal.title}?" }, class: "button is-danger is-small is-hidden", id: "goal-delete-button" do %>
  <span>Delete</span>
  <span class="icon is-small">
    <i class="fas fa-times"></i>
  </span>
<% end %>

app/views/shared/_modal_goal_edit_footer.html.erb
<div class=level>
  <div class="level-left">
    <div class="level-item">
      <a class="button is-primary" onclick="document.getElementById('edit-form-update').click()">Save</a>
    </div>
    <div class="level-item">
      <button class="button close-modal">Close</button>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <a class="has-text-danger" onclick="document.getElementById('goal-delete-button').click()">Delete</a>
    </div>
  </div>
</div>

app/views/shared/_modal_goal_edit_header.html.erb
<div class="columns">
    <div class="column has-text-left">
      <%= link_to "← Back", goal_path(@goal, horizon: @horizon, term: @term), class: "", remote: true %>
    </div>
    <div class="column has-text-centered">
      <p class="modal-card-title">Edit Goal</p>
    </div>
    <div class="column has-text-right">
      <button class="delete close-modal" aria-label="close"></button>
    </div>
  </div>
</div>

app/views/shared/_modal_goal_new.html.erb
<div class="buttons has-addons">
  <%= link_to "Weekly", new_goal_path(horizon: "week"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'week'}" %>
  <%= link_to "Quarterly", new_goal_path(horizon: "quarter"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'quarter'}" %>
  <%= link_to "Yearly", new_goal_path(horizon: "year"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'year'}" %>
  <%= link_to "Life", new_life_goal_path, remote: true, class: "button modal-button #{'is-select is-info' if request.path_info.include?('life_goals')}" %>
</div>

<%= form_with model: @goal, url: goals_path(horizon: @horizon), id: "new-goal-form", local: true, data:{remote: true} do |f| %>
  <p><%= @goal.errors[:date].first %></p>
  <div class="field">
    <label class="heading">Title</label>
    <div class="control">
      <%= f.text_field :title, class: "input"%>
    </div>
    <p id="title-error" class="help is-danger"><%= @goal.errors[:title].first %></p>
  </div>
  <div class="field">
    <label class="heading">Description</label>
    <div class="control">
      <%= f.text_area :description, class: "textarea"%>
    </div>
  </div>

  <div class="field">
    <div class="control">
        <%= f.hidden_field :horizon, :value => params[:horizon] %>
    </div>
  </div>

  <div class="field">
    <label class="heading">Parent Goal</label>
    <div class="control">
      <div class="select">
        <%= f.select :parent_goal_id, options_from_collection_for_select(@parent_goals, 'id', 'title'), include_blank: true %>
      </div>
    </div>
  </div>

  <div class="field">
    <label class="heading">Due Date</label>
    <div class="control">
      <%= f.radio_button :date, DateTime.current.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'), :checked => true, id:"radio-this", class: "is-checkradio" %>
      <label for="radio-this">
        This <%= @horizon.capitalize %>
      </label>
      <%= f.radio_button :date, next_term("#{@horizon}").from_now.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'), id:"radio-next", class: "is-checkradio" %>
      <label for="radio-next">
        Next <%= @horizon.capitalize %>
      </label>
    </div>
  </div>

  <br/>
  
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Save", class: "button is-primary is-hidden", id: "new-save-button", remote: true %>
    </div>
    <div class="control">
      <%= link_to "Cancel", goals_path(horizon: @horizon), class: "button is-hidden", id: "new-cancel-button" %>
    </div>
  </div>
<% end %>

app/views/shared/_modal_goal_show.html.erb
<div class="columns">
  <div class="column is-three-quarters">
      <div class="title is-3 is-spaced"><%= @goal.title %></div>
  </div>
  <div class="column has-text-right">
    <% if @goal.achievement == "achieved" %>
      <div class="tag is-success is-light"><%= @goal.achievement.capitalize %></div>
    <% elsif @goal.achievement == "partially achieved" %>
      <div class="tag is-warning is-light"><%= @goal.achievement.capitalize %></div>
    <% elsif @goal.achievement == "failed" %>
      <div class="tag is-danger is-light"><%= @goal.achievement.capitalize %></div>
    <% else %>
      <div class="tag is-light">Not achieved yet</div>
    <% end %>
  </div>
</div>
    
<div class="columns">
  <div class="column">
    <div class="heading">Due Date</div>
    <div><%= @goal.date %></div>
  </div>
  <div class="column">
    <% if @parent_goal.present? %>
      <div class="heading">Parent Goal</div>
      <div>
        <%= @parent_goal.title %>
      </div>
    <% end %>
  </div>
</div>

<% unless @goal.description.blank? %>
  <div class="">
    <div class="heading">Description</div>
    <div><%= simple_format(@goal.description) %></div>
  </div>
<% end %>
<br/>
<% if @horizon != "week" %>
  <% if @children_goals.count > 0 %>
    <div class="">
      <div class="heading">Children Goals</div>
      <div class="bullet children-goals">
        <ul>
        <% @children_goals.each do |goal| %>
          <li class=""><%= goal.title %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_modal_goal_show_footer.html.erb
<%= link_to "Edit", edit_goal_path(horizon: @horizon, term: @term), class: "button is-primary", remote: true %>
<button class="button close-modal">Close</button>

app/views/shared/_modal_goal_show_header.html.erb
<div class="columns">
  <div class="column"></div>
  <div class="column is-four-fifths has-text-centered">
    <p class="modal-card-title">Goal Details</p>
  </div>
  <div class="column has-text-right">
    <button class="delete close-modal" aria-label="close"></button>
  </div>
</div>

app/views/shared/_modal_lifegoal_edit.html.erb
<%= form_with model: @life_goal, url: life_goal_path(@life_goal), local: true, data:{remote: true} do |f| %>
  
  <div class="field"> 
    <p class="heading">Title</p>
    <div class="control">
      <%= f.text_field :title, class: "input" %>
    </div>
    <p id="title-error" class="help is-danger"><%= @life_goal.errors[:title].first %></p>
  </div>

  <div class="field">
    <p class="heading">What</p>
    <div class="control">
      <%= f.text_area :what, class: "textarea" %>
    </div>
  </div>

   <div class="field">
    <p class="heading">Why</p>
    <div class="control">
      <%= f.text_area :why, class: "textarea" %>
    </div>
  </div>

  <!-- this submit button is triggered from the button in the _modal_goal_edit_save partial -->
  <p class="is-hidden"><%= f.submit "Update", id: "edit-form-update" %></p>

<% end %>

<%= link_to life_goal_path(@life_goal), method: :delete, data: { confirm: "Delete Goal: #{@life_goal.title}?" }, class: "button is-danger is-small is-hidden", id: "goal-delete-button" do %>
  <span>Delete</span>
  <span class="icon is-small">
    <i class="fas fa-times"></i>
  </span>
<% end %>

app/views/shared/_modal_lifegoal_edit_footer.html.erb
<nav class=level>
  <div class="level-left">
    <div class="level-item">
      <a class="button is-primary" onclick="document.getElementById('edit-form-update').click()">Save</a>
    </div>
    <div class="level-item">
      <button class="button close-modal">Close</button>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <a class="has-text-danger" onclick="document.getElementById('goal-delete-button').click()">Delete</a>
    </div>
  </div>
</nav>

app/views/shared/_modal_lifegoal_edit_header.html.erb
<div class="columns">
    <div class="column has-text-left">
      <%= link_to "← Back", life_goal_path(@life_goal), class: "", remote: true %>
    </div>
    <div class="column has-text-centered">
      <p class="modal-card-title">Edit Goal</p>
    </div>
    <div class="column has-text-right">
      <button class="delete close-modal" aria-label="close"></button>
    </div>
  </div>
</div>

app/views/shared/_modal_lifegoal_new.html.erb
<div class="buttons has-addons">
  <%= link_to "Weekly", new_goal_path(horizon: "week"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'week'}" %>
  <%= link_to "Quarterly", new_goal_path(horizon: "quarter"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'quarter'}" %>
  <%= link_to "Yearly", new_goal_path(horizon: "year"), remote: true, class: "button modal-button #{'is-select is-info' if @horizon == 'year'}" %>
  <%= link_to "Life", new_life_goal_path, remote: true, class: "button modal-button #{'is-select is-info' if request.path_info.include?('life_goals')}" %>
</div>

<%= form_with model: @life_goal, url: life_goals_path, id: "new-life-goal-form", local: true, data:{remote: true} do |f| %>
  <div class="field">
    <label class="heading">ROLE - I want to be...</label>
    <div class="control">
      <%= f.text_field :title, class: "input"%>
    </div>
    <p id="title-error" class="help is-danger"><%= @life_goal.errors[:title].first %></p>
  </div>
  <div class="field">
    <label class="heading">WHAT - It looks/feels like...</label>
    <div class="control">
      <%= f.text_area :what, class: "textarea"%>
    </div>
  </div>
    <div class="field">
    <label class="heading">WHY - In order to...</label>
    <div class="control">
      <%= f.text_area :why, class: "textarea"%>
    </div>
  </div>

  <br/>
  
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Save", class: "button is-primary is-hidden", id: "new-save-button" %>
    </div>
    <div class="control">
      <%= link_to "Cancel", life_goals_path, class: "button is-hidden" %>
    </div>
  </div>
<% end %>

app/views/shared/_modal_lifegoal_show_footer.html.erb
<%= link_to "Edit", edit_life_goal_path, class: "button is-primary", remote: true %>
<button class="button close-modal">Close</button>

app/views/shared/_navigation.html.erb
<div class="menu">
  <div id="menu-container">
    <div id="menu-top">
      <div id="menu-app-name">
        <h1 class="title is-4 has-text-centered has-text-white">Goal App</h1>
      </div>
      <div id="menu-collapse-button" onclick="menu_collapse('side-menu')">
          <%= embedded_svg("backburger.svg", class:"burger-svg") %>
      </div>
    </div>
    <% if logged_in? %>
    <ul class="menu-list">
      <li><a href="/">HOME</a></li>
      <li><a href="/goals?horizon=week&term=term_this">Weekly goals</a></li>
      <li><a href="/goals?horizon=quarter&term=term_this">Quarterly goals</a></li>
      <li><a href="/goals?horizon=year&term=term_this">Yearly goals</a></li>
      <li><a href="/life_goals">Life goals</a></li>
    </ul>
    <div id="menu-login">
      <div class="has-text-light has-text-centered is-size-7">
        Logged In as:
        <span class="has-text-light has-text-weight-bold is-size-7"><%= current_user.email %></span>
      </div>
      <%= link_to "Log Out", logout_path, class: "button is-small is-light is-outlined" %>
    </div>
    <% else %>
    <div id="menu-login">
      <%= link_to "Log In", login_path, class: "button is-small is-light is-outlined" %>
    </div>
    <% end %>
  </div>
</div>