config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  resources :goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :life_goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'


resources :admin

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include GoalsHelper

  validates :title, presence: {message: "Goals must have a title."}
  validates :date, presence: {message: "Goals must have a deadline."}
  validates :horizon, presence: {message: "Goals must have a horizon."}
  validates :horizon, inclusion: { in: %w(week quarter year), message: "%{value} is not a valid horizon" }
  validates :achievement, inclusion: { in: ['achieved', 'partially achieved', 'failed', nil, ''], message: "%{value} is not a valid achievement" }

  belongs_to :user

  scope :date_later_than, ->(start_date) { where('date >= ?', start_date) }

  def this_term?(horizon)
    date >= DateTime.current.to_date.send("beginning_of_#{horizon}") && date <= DateTime.current.to_date.send("end_of_#{horizon}")
  end

  def next_term?(horizon)
    date >= next_term(horizon).from_now.to_date.send("beginning_of_#{horizon}") && date <= next_term(horizon).from_now.to_date.send("end_of_#{horizon}")
  end

end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: {message: "must be present."}
  validates :email, uniqueness: {message: "already exists."}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
  
  has_many :goals
  has_many :life_goals

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @horizon = params[:horizon]
    @term = params[:term]
    def goals_scope(horizon, term)
      if term == "term_previous"
        Goal.where(user: current_user).where(horizon: horizon).where('date < ?', DateTime.current.to_date.send("beginning_of_#{horizon}"))
      elsif term == "term_next"
        Goal.where(user: current_user).where(horizon: horizon).where('date > ?', DateTime.current.to_date.send("end_of_#{horizon}"))
      else
        Goal.where(user: current_user).where(horizon: horizon).where('date >= ?', DateTime.current.to_date.send("beginning_of_#{horizon}")).where('date <= ?', DateTime.current.to_date.send("end_of_#{horizon}"))
      end
    end
    @goals = goals_scope(@horizon, @term)
    @allgoals = Goal.all.where(user: current_user)
    @lifegoals = LifeGoal.all.where(user: current_user)
  end
  
  def show
    @horizon = params[:horizon]
    @term = params[:term]
    id = params[:id]
    @goal = Goal.find(id)
    @parent_goal = parent_goal(@goal.parent_goal_id, @horizon)
    @children_goals = children_goals(@goal.id, @horizon)
    respond_to do |format|
      format.js
    end
  end

  def new
    @horizon = params[:horizon]
    @goal = Goal.new
    @parent_goals = []
    if parent_goals(@horizon, "term_this").where(user: current_user).present?
      @parent_goals = parent_goals(@horizon, "term_this").where(user: current_user)
    end
    respond_to do |format|
      format.js
    end
  end

  def edit
    @horizon = params[:horizon]
    @term = params[:term]
    id = params[:id]
    @goal = Goal.find(id)
    @parent_goals = []
    if parent_goals(@horizon, @term).where(user: current_user).present?
      @parent_goals = parent_goals(@horizon, @term).where(user: current_user)
    end
    respond_to do |format|
      format.js
    end
  end

  def create
    @horizon = params[:horizon]
    @term = params[:term]
    @goal = Goal.new(goal_params.merge(user: current_user))
    if @goal.save
      render js: "window.location='#{goals_path(horizon: @horizon, term:
        if @goal.date >= DateTime.current.to_date.send("beginning_of_#{@horizon}") && @goal.date <= DateTime.current.to_date.send("end_of_#{@horizon}")
          "term_this"
        elsif @goal.date >= helpers.next_term(@horizon).from_now.to_date.send("beginning_of_#{@horizon}") && @goal.date <= helpers.next_term(@horizon).from_now.to_date.send("end_of_#{@horizon}")
          "term_next"
        end
      )}'"
    else
      respond_to do |format|
        format.js 
      end
    end
  end

  def update
    @horizon = params[:horizon]
    @term = params[:term]
    id = params[:id]
    @goal = Goal.find(id)
    if @goal.update(goal_params)
      render js: "window.location='#{goals_path(horizon: @horizon, term: 
        if @goal.date >= DateTime.current.to_date.send("beginning_of_#{@horizon}") && @goal.date <= DateTime.current.to_date.send("end_of_#{@horizon}")
          "term_this"
        elsif @goal.date >= helpers.next_term(@horizon).from_now.to_date.send("beginning_of_#{@horizon}") && @goal.date <= helpers.next_term(@horizon).from_now.to_date.send("end_of_#{@horizon}")
          "term_next"
        elsif @goal.date < DateTime.current.to_date.send("beginning_of_#{@horizon}")
          "term_previous"
        end
      )}'"
    else
      respond_to do |format|
        format.js 
      end
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    if Goal.where(parent_goal_id: params[:id]).where.not(horizon: "year").present?
      @children_goals = Goal.where(parent_goal_id: params[:id]).where.not(horizon: "year")
      @children_goals.each do |children_goal|
        children_goal[:parent_goal_id] = nil
        children_goal.save
      end
    end
    @goal.destroy
    redirect_to action: "index", horizon: @goal[:horizon], term: 
    if @goal.date >= DateTime.current.to_date.send("beginning_of_#{@goal[:horizon]}") && @goal.date <= DateTime.current.to_date.send("end_of_#{@goal[:horizon]}")
      "term_this"
    elsif @goal.date >= helpers.next_term(@goal[:horizon]).from_now.to_date.send("beginning_of_#{@goal[:horizon]}") && @goal.date <= helpers.next_term(@goal[:horizon]).from_now.to_date.send("end_of_#{@goal[:horizon]}")
      "term_next"
    elsif @goal.date < DateTime.current.to_date.send("beginning_of_#{@goal[:horizon]}")
      "term_previous"
    else
      "term_this"
    end
  end

  def edit_multiple
    @horizon = params[:horizon]
    @term = params[:term]
    @goal = Goal.find(params[:goal_ids])
    @parent_horizon = parent_horizon(@horizon)
    @parent_goals = parent_goals(@horizon, "term_previous").where(user: current_user)
  end

  def update_multiple
    @horizon = params[:horizon]
    @term = params[:term]
    @parent_horizon = parent_horizon(@horizon)
    @parent_goals = parent_goals(@horizon, "term_previous").where(user: current_user)
    @goal = Goal.update(params[:goal].keys, params[:goal].values)
    if @goal.map { |goal| goal.errors.any? }.exclude?(true)
      redirect_to goals_path(horizon: @horizon, term: "term_this")
    else
      render edit_multiple_goals_path
    end
  end

  private
  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  def goal_params
    params.require(:goal).permit(:title, :description, :achievement, :date, :horizon, :parent_goal_id, :term)
  end

  def parent_horizon(horizon)
    if horizon == "week"
      "quarter"
    elsif horizon == "quarter"
      "year"
    elsif horizon == "year"
      "life"
    end
  end

  def parent_goals(horizon, term)
    if horizon == "week" || horizon == "quarter"
      if term == "term_previous"
        Goal.where(horizon: parent_horizon(horizon))
      elsif term == "term_this" || term == "term_next"
        Goal.where(horizon: parent_horizon(horizon)).where('date >= ?', DateTime.current.to_date.send("beginning_of_#{parent_horizon(horizon)}"))
      end
    elsif horizon == "year"
      LifeGoal.all
    end
  end

  def parent_goal(parent_goal_id, horizon)
    if parent_goal_id.present?
      if horizon == "week" ||  horizon == "quarter"
        Goal.find(parent_goal_id)
      elsif @horizon == "year"
        LifeGoal.find(parent_goal_id)
      end
    else
      ""
    end
  end

  def parent_horizon_start(horizon)
    DateTime.current.to_date.send("beginning_of_#{parent_horizon(horizon)}")
  end

  def children_goals(id, horizon)
    if horizon == "quarter"
      Goal.where(horizon: "week").where(parent_goal_id: id)
    elsif horizon == "year"
      Goal.where(horizon: "year").where(parent_goal_id: id)
    else
      nil
    end
  end
  
end

app/helpers/goals_helper.rb
module GoalsHelper
  
  def next_term(horizon)
    if horizon == "week"
      1.week
    elsif horizon == "quarter"
      3.months
    elsif horizon == "year"
      1.year
    end
  end

  

end

app/views/goals/create.js.erb
$('#title-error').html('<%= @goal.errors[:title].first %>');
<% if @goal.errors[:title].any? %>
  $("#goal_title").addClass("is-danger");
  $( "#goal_title" ).focus();
<% else %>
  $("#goal_title").removeClass("is-danger");
<% end %>

app/views/goals/edit.html.erb
<%= form_with model: @goal, url: goal_path(@goal), local: true do |f| %>
  <% if @goal.this_term?(@horizon) || @goal.next_term?(@horizon) %>
  <p>Date:</p>
    <p>
      <label><%= f.radio_button :date, DateTime.current.to_date.beginning_of_week.strftime('%Y-%m-%d'),
      :checked => !!(@goal.this_term?(@horizon)) %>This Week</label>
    </p>
    <p>
      <label><%= f.radio_button :date, 1.week.from_now.to_date.end_of_week.strftime('%Y-%m-%d'),
      :checked => !!(@goal.next_term?(@horizon)) %>Next Week</label>
    </p>
  <%end%>
  <p><%= @goal.errors[:date].first %></p>
  <p><%= f.text_field :title %></p>
  <p><%= @goal.errors[:title].first %></p>
  <p><%= f.text_area :description %></p>
  <p><%= f.select :achievement, options_for_select(["Achieved", "Partially achieved", "Failed"], @goal.achievement), include_blank: true %></p>
  <p><%= f.submit "Update" %></p>
<% end %>
<td>
<%= link_to goal_path(@goal, horizon: @horizon), method: :delete, data: { confirm: "Delete Goal: #{@goal.title}?" }, remote: true, class: "button is-danger is-small is-outlined" do %>
  <span>Delete</span>
  <span class="icon">
    <i class="fas fa-times"></i>
  </span>
<% end %>
<%= link_to "Cancel", goals_path(horizon: @horizon), class: "button" %>

app/views/goals/edit.js.erb
$('#modal-content').html('<%= j render partial: "shared/modal_goal_edit" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_goal_edit_footer" %>');
$('#modal-header').html('<%= j render partial: "shared/modal_goal_edit_header" %>');

app/views/goals/edit_multiple.html.erb
<div class="section">

  <%= form_with model: @goal, url: update_multiple_goals_path(horizon: @horizon), local: true, method: :patch do %>
    <table class="table is-fullwidth">
      <tr>
        <th>
          <p>#</p>
        </th>
        <th>
          <p>Title</p>
        </th>
        <th>
          <p>Description</p>
        </th>
        <th>
          <p>Parent Goal (<%= @parent_horizon.capitalize %>)</p>
        </th>
        <th>
          <p>Date</p>
        </th>
        <th>
          <p>Achievement</p>
        <th>
        </th>
      </tr>
      <% @i = 1%>
      <% @goal.each do |goal| %>
        <%= fields_for "goal[]", goal do |f| %>
          <tr>
            <td>
              Goal #<%= @i %>
            </td>
            <td class="field">
              <div class="control">
                <% if goal.errors[:title].any? %>
                  <%= f.text_field :title, class: "input is-danger"%>
                <% else %>
                  <%= f.text_field :title, class: "input"%>
                <%end%>
              </div>
              <p id="title-error" class="help is-danger"><%= goal.errors[:title].first %></p>
            </td>
            <td class="field">
              <div class="control">
                <%= f.text_area :description, class: "textarea" %>
              </div>
            </td>
            <td class="field">
              <div class="control">
                <div class="select">
                  <%= f.select :parent_goal_id, options_from_collection_for_select(@parent_goals, 'id', 'title', goal.parent_goal_id), include_blank: true %>
                </div>
              </div>
            </td>
            <td class="field">
              <div class="control">
                <%= f.radio_button :date, DateTime.current.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'),
                :checked => !!(goal.this_term?(@horizon)), id: "radio-thisterm-#{goal.id}", class: "is-checkradio", onclick: "customeDate(#{goal.id})" %>
                <label for="radio-thisterm-<%= goal.id %>">
                  This <%= @horizon %>
                </label>
                <br/>
                <%= f.radio_button :date, next_term(@horizon).from_now.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'),
                :checked => !!(goal.next_term?(@horizon)), id: "radio-nextterm-#{goal.id}", class: "is-checkradio", onclick: "customeDate(#{goal.id})" %>
                <label for="radio-nextterm-<%= goal.id %>">
                  Next <%= @horizon %>
                </label>
                <br/>
                <%= f.radio_button :date, "", :checked => !(!!(goal.this_term?(@horizon)) || !!(goal.next_term?(@horizon))), id: "radio-customterm-#{goal.id}", class: "is-checkradio", onclick: "customeDate(#{goal.id})" %>
                <label for="radio-customterm-<%= goal.id %>">
                  Custom
                </label>
                <%= f.date_field :date, value: goal.date, id: "date-picker-#{goal.id}", class: (params[:term]=='term_previous' ? "" : "is-hidden") %>
              </div>
            </td>
            <td class="field">
              <div class="control">
                <div class="select">
                  <%= f.select :achievement, options_for_select({"Achieved" => "achieved", "Partially achieved" => "partially achieved", "Failed" => "failed"}, goal.achievement), include_blank: true %>
                </div>
              </div>
            </td>
            <td>
              <%= link_to goal_path(goal, horizon: @horizon, term: params[:term]), method: :delete, data: { confirm: "Delete Goal: #{goal.title}?" }, class: "button is-danger is-small is-outlined" do %>
                <span>Delete</span>
                <span class="icon is-small">
                  <i class="fas fa-times"></i>
                </span>
              <% end %>
            </td>
          </tr>
          <% @i += 1 %>
        <% end %>
      <% end %>
    </table>
    <div class="field is-grouped">
      <div class="control">
        <%= submit_tag "Update", class: "button is-primary" %>
      </div>
      <div class="control">
        <%= link_to "Cancel", goals_path(horizon: @horizon, term: @term), class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/goals/index.html.erb
<div class="section">

  <div class="tabs is-medium is-boxed">
    <ul>
      <li class="term-selector <% if params[:term] == "term_previous" %>is-active<% end %>">
        <a href="/goals?horizon=<%= @horizon %>&term=term_previous">Previous <%= @horizon.capitalize.+"s" %></a>
      </li>
      <li class="term-selector <% if params[:term] == "term_this" %>is-active<% end %>">
        <a href="/goals?horizon=<%= @horizon %>&term=term_this">This <%= @horizon.capitalize %></a>
      </li>
      <li class="term-selector <% if params[:term] == "term_next" %>is-active<% end %>">
        <a href="/goals?horizon=<%= @horizon %>&term=term_next">Next <%= @horizon.capitalize %></a>
      </li>
    </ul>
  </div>

  <% if @goals.count == 0 %>
    <div class="no-results">
      <%= image_tag "no_results.png", id: "no-results-image" %>
      <div class="has-text-grey">You don't have any goal for 
      <% if @term == "term_previous" %>
        these past few <%=@horizon%>s!
      <% elsif @term == "term_this" %>
        this <%=@horizon%>!
      <% elsif @term == "term_next" %>
        next <%=@horizon%>!
      <% end %>
      </div>
    </div>
  <% end %>

  <% @goals.group_by{ |goal| goal.date.send("beginning_of_#{@horizon}")}.sort.reverse.each do |term_start, goals|%>
    <div id="term-group" class="container">
      <%= form_with model: @goal, url: edit_multiple_goals_path, local: true, method: :get do %>
        <div class="<%= term_start %>">
          <div class="level">
            <div class="level-left">
              <div class="level-item subtitle">
                <% end_of_horizon = term_start.send("end_of_#{@horizon}")%>
                <%if @horizon == "week" %>
                  <%= @horizon.capitalize%> until 
                  <%= end_of_horizon.strftime("%b. #{end_of_horizon.day.ordinalize} (%a), %Y") %>
                <% elsif @horizon == "quarter" %>
                  Q<%= ((end_of_horizon.month.to_f)/3).ceil %>
                  <%= end_of_horizon.strftime("%Y") %>
                  (until end of <%= end_of_horizon.strftime("%B")%>)
                <% elsif @horizon == "year" %>
                  Year <%= end_of_horizon.strftime("%Y")%>
                <% end %>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <%= submit_tag "Update goals", class: "button is-small is-outlined is-primary level-item" %>
              </div>
            </div>
          </div>
          <table class="table is-fullwidth">
            <tr>
              <th>
              </th>
              <th>
                <p>Title</p>
              </th>
              <th class="is-hidden">
                <p>Description</p>
              </th>
              <th>
                <p>Parent Goal</p>
              </th>
              <th>
                <p>Achievment</p>
              </th>
              <th class="is-hidden">
                <p>Date</p>
              </th>
              <th class="is-hidden"></th>
            </tr>
            <% @i = 1%>
            <%= hidden_field_tag "horizon", @horizon %>
            <%= hidden_field_tag "term", @term %>
            <% goals.each do |goal|%>
              <tr>
                <td>
                  #<%= @i %>
                  <%= hidden_field_tag "goal_ids[]", goal.id %>
                </td>
                <td>
                  <%= link_to goal.title, goal_path(goal, horizon: @horizon, term: @term), class: "modal-button",remote: true %>
                </td>
                <td class="is-hidden">
                  <%= simple_format(goal.description) %>
                </td>
                <td>
                  <% if goal.parent_goal_id.present? == true %>
                    <% if @horizon == "year" %>
                      <%= link_to @lifegoals.find(goal.parent_goal_id).title, life_goal_path(goal.parent_goal_id), class: "modal-button",remote: true %>
                    <% else%>
                      <%= link_to @allgoals.find(goal.parent_goal_id).title, goal_path(goal.parent_goal_id,horizon: @horizon, term: @term), class: "modal-button",remote: true %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <% if goal.achievement == "achieved" %>
                    <span class="tag is-success is-light"><%= goal.achievement.capitalize %></span>
                  <% elsif goal.achievement == "partially achieved" %>
                    <span class="tag is-warning is-light"><%= goal.achievement.capitalize %></span>
                  <% elsif goal.achievement == "failed" %>
                    <span class="tag is-danger is-light"><%= goal.achievement.capitalize %></span>
                  <% else %>
                  <% end %>
                </td>
                <td class="is-hidden">
                  <%= goal.date %>
                </td>
                <td class="is-hidden">
                  <%= link_to  "Edit", edit_goal_path(goal), class: "button is-link" %>
                </td>
              </tr>
              <% @i += 1 %>
            <%end%>
          </table>
          <hr/>
          <br/>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div id="modal-window" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <div id="modal-header"></div>
      <button id="modal-close-button" class="delete is-hidden" aria-label="close"></button>
    </header>
    <section id="modal-content" class="modal-card-body">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <div id="modal-footer"></div>
      <button class="button is-hidden" id="modal-close-button">Close</button>
    </footer>
  </div>
</div>

app/views/goals/new.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <h2 class="title">Create a New Goal</h2>
    </div>
  </div>
</div>

<div class="buttons has-addons">
  <a href="/goals/new?horizon=week" class="button <%= 'is-select is-info' if @horizon == 'week' %>">Weekly</a>
  <a href="/goals/new?horizon=quarter" class="button <%= 'is-select is-info' if @horizon == 'quarter' %>">Quarterly</a>
  <a href="/goals/new?horizon=year" class="button <%= 'is-select is-info' if @horizon == 'year' %>">Yearly</a>
</div>

<%= form_with model: @goal, url: goals_path(horizon: @horizon), id: "new-goal-form", local: true do |f| %>
  <p><%= @goal.errors[:date].first %></p>
  <div class="field">
    <label class="label">Title</label>
    <div class="control">
      <%= f.text_field :title, class: "input"%>
    </div>
    <p><%= @goal.errors[:title].first %></p>
  </div>
  <div class="field">
    <label class="label">Description</label>
    <div class="control">
      <%= f.text_area :description, class: "textarea"%>
    </div>
  </div>

  <div class="field">
    <div class="control">
        <%= f.hidden_field :horizon, :value => params[:horizon] %>
    </div>
  </div>

  <div class="field">
    <label class="label">Due Date</label>
    <div class="control">
      <%= f.radio_button :date, DateTime.current.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'), :checked => true, id:"radio-this", class: "is-checkradio" %>
      <label for="radio-this">
        This <%= @horizon.capitalize %>
      </label>
      <%= f.radio_button :date, next_term("#{@horizon}").from_now.to_date.send("end_of_#{@horizon}").strftime('%Y-%m-%d'), id:"radio-next", class: "is-checkradio" %>
      <label for="radio-next">
        Next <%= @horizon.capitalize %>
      </label>
    </div>
  </div>

  <div class="field">
    <label class="label">Related goal</label>
    <div class="control">
      <div class="select">
        <%= f.select :parent_goal_id, options_from_collection_for_select(@parent_goals, 'id', 'title'), include_blank: true %>
      </div>
    </div>
  </div>

  <br/>
  
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Save", class: "button is-primary" %>
    </div>
    <div class="control">
      <%= link_to "Cancel", goals_path(horizon: @horizon), class: "button" %>
    </div>
  </div>
<% end %>

app/views/goals/new.js.erb
$('#modal-header').html('<%= j render partial: "shared/modal_goal_new_header" %>');
$('#modal-content').html('<%= j render partial: "shared/modal_goal_new" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_goal_new_footer" %>');

app/views/goals/quarterly_index.html.erb
<%= render partial: "shared/goalheader", locals: {horizon: @horizon} %>

<% @goals.group_by{ |u| u.date.beginning_of_quarter }.sort.reverse.each do |quarter_start, goals|%>
  <div id="week" class="container">
    <%= form_tag edit_multiple_goals_path, method: :get do %>
    <hr/>
    <div class="level">
      <div class="level-left">
        <h2 class="subtitle level-item">
          <% if DateTime.current.to_date.beginning_of_quarter == quarter_start %>
            This quarter
          <% elsif DateTime.current.to_date.beginning_of_quarter + 3.month == quarter_start %>
            Next quarter
          <% else %>
            Previous quarter ~ <%= quarter_start.end_of_quarter %>
          <% end %>
        </h2>
      </div>
      <div class="level-right">
        <%= submit_tag "Update goals", class: "button is-small is-outlined is-primary level-item" %>
      </div>
    </div>
      <table class="table is-fullwidth">
        <tr>
          <th>
            <p>#</p>
          </th>
          <th>
            <p>Title</p>
          </th>
          <th>
            <p>Description</p>
          </th>
          <th>
            <p>Achievment</p>
          </th>
          <th class="is-hidden"></th>
        </tr>
        <% @i = 1%>
        <% goals.each do |goal|%>
          <tr>
            <td>
              Goal #<%= @i %>
              <%= hidden_field_tag "goal_ids[]", goal.id %>
            </td>
            <td>
              <%= link_to goal.title, goal_path(goal) %>
            </td>
            <td>
              <%= goal.description %>
            </td>
            <td>
              <% if goal.achievement == "Achieved" %>
                <span class="tag is-success is-light"><%= goal.achievement %></span>
              <% elsif goal.achievement == "Partially achieved" %>
                <span class="tag is-warning is-light"><%= goal.achievement %></span>
              <% elsif goal.achievement == "Failed" %>
                <span class="tag is-danger is-light"><%= goal.achievement %></span>
              <% else %>
              <% end %>
            </td>
            <td class="is-hidden">
              <%= link_to  "Edit", edit_goal_path(goal), class: "button is-link" %>
            </td>
          </tr>
          <% @i += 1 %>
        <%end%>
      </table>
      <br/>
    <% end %>
  </div>
<% end %>

app/views/goals/show.html.erb
<h2>Date:</h2>
<%= @goal.date %>
<h2>Title:</h2>
<%= @goal.title %>
<h2>Description:</h2>
<%= @goal.description %>
<h2>Horizon:</h2>
<%= @goal.horizon %>
<h2>Related goal:</h2>
<%= @goal.parent_goal_id %>
<h2>Achievement:</h2>
<%= @goal.achievement %>
<%= link_to "Cancel", goals_path(horizon: @horizon), class: "button" %>

app/views/goals/show.js.erb
$('#modal-header').html('<%= j render partial: "shared/modal_goal_show_header" %>');
$('#modal-content').html('<%= j render partial: "shared/modal_goal_show" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_goal_show_footer" %>');

app/views/goals/update.js.erb
$('#title-error').html('<%= p.errors[:title].first %>');
<% if p.errors[:title].any? %>
  $("#goal_title").addClass("is-danger");
  $( "#goal_title" ).focus();
<% else %>
  $("#goal_title").removeClass("is-danger");
<% end %>