config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  resources :goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :life_goals do
    collection do
      get :edit_multiple
      patch :update_multiple
    end
  end

  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'


resources :admin

end

app/models/life_goal.rb
class LifeGoal < ActiveRecord::Base

  validates :title, presence: {message: "Goals must have a title."}

  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: {message: "must be present."}
  validates :email, uniqueness: {message: "already exists."}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
  
  has_many :goals
  has_many :life_goals

end

app/controllers/life_goals_controller.rb
class LifeGoalsController < ApplicationController

  def index
    @life_goals = LifeGoal.all.where(user: current_user)
  end

  def show
    id = params[:id]
    @life_goal = LifeGoal.find(id)
    @children_goals = children_goals(@life_goal.id)
    respond_to do |format|
      format.js
    end
  end

  def new
    @life_goal = LifeGoal.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @life_goal = LifeGoal.new(life_goal_params.merge(user: current_user))
    if @life_goal.save
      render js: "window.location='#{life_goals_path}'"
    else
      respond_to do |format|
        format.js 
      end
    end
  end

  def edit
    id = params[:id]
    @life_goal = LifeGoal.find(id)
  end

  def update
    id = params[:id]
    @life_goal = LifeGoal.find(id)
    if @life_goal.update(life_goal_params)
      render js: "window.location='#{life_goals_path}'"
    else
      respond_to do |format|
        format.js 
      end
    end
  end

  def destroy
    @life_goal = LifeGoal.find(params[:id])
    if Goal.where(horizon: "year").where(parent_goal_id: params[:id]).present?
      @children_goals = Goal.where(horizon: "year").where(parent_goal_id: params[:id])
      @children_goals.each do |children_goal|
        children_goal[:parent_goal_id] = nil
        children_goal.save
      end
    end
    @life_goal.destroy
    redirect_to action: "index"
  end

  def edit_multiple
    @life_goals = LifeGoal.all.where(user: current_user)
  end

  def update_multiple
    @life_goals = LifeGoal.update(params[:life_goal].keys, params[:life_goal].values)
    if @life_goals.map { |goal| goal.errors.any? }.exclude?(true)
      redirect_to life_goals_path(horizon: @horizon, term: "term_this")
    else
      render edit_multiple_life_goals_path
    end
  end

  private

  def life_goal_params
    params.require(:life_goal).permit(:title, :what, :why)
  end

  def children_goals(id)
    Goal.where(horizon: "year").where(parent_goal_id: id)
  end

end

app/helpers/life_goals_helper.rb
module LifeGoalsHelper
end

app/views/life_goals/create.js.erb
$('#title-error').html('<%= @life_goal.errors[:title].first %>');
<% if @life_goal.errors[:title].any? %>
  $("#life_goal_title").addClass("is-danger");
  $( "#life_goal_title" ).focus();
<% else %>
  $("#life_goal_title").removeClass("is-danger");
<% end %>

app/views/life_goals/edit.html.erb
<%= form_with model: @life_goal, url: life_goal_path(@life_goal), local: true do |f| %>
  <p><%= f.text_field :title %></p>
  <p><%= f.text_area :what %></p>
  <p><%= f.text_area :why %></p>
  <p><%= f.submit "Update" %></p>
<% end %>
<%= link_to life_goal_path(@life_goal), method: :delete, data: { confirm: "Delete Goal: #{@life_goal.title}?" }, remote: true, class: "button is-danger is-small is-outlined" do %>
  <span>Delete</span>
  <span class="icon">
    <i class="fas fa-times"></i>
  </span>
<% end %>
<%= link_to "Cancel", life_goals_path, class: "button" %>

app/views/life_goals/edit.js.erb
$('#modal-header').html('<%= j render partial: "shared/modal_lifegoal_edit_header" %>');
$('#modal-content').html('<%= j render partial: "shared/modal_lifegoal_edit" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_lifegoal_edit_footer" %>');

app/views/life_goals/edit_multiple.html.erb
<div class="section">

  <%= form_with model: @life_goals, url: update_multiple_life_goals_path, local: true, method: :patch do %>
    <table class="table is-fullwidth">
      <tr>
        <th>
          <p>#</p>
        </th>
        <th>
          <p>ROLE</p>
        </th>
        <th>
          <p>WHAT</p>
        </th>
        <th>
          <p>WHY</p>
        </th>
        <th></th>
      </tr>
      <% @i = 1%>
      <% @life_goals.each do |life_goal| %>
        <%= fields_for "life_goal[]", life_goal do |f| %>
          <tr>
            <td>
              Goal #<%= @i %>
            </td>
            <td class="field">
              <div class="control">
                <% if life_goal.errors[:title].any? %>
                  <%= f.text_field :title, class: "input is-danger" %>
                <%else%>
                  <%= f.text_field :title, class: "input" %>
                <%end%>
              </div>
              <p id="title-error" class="help is-danger"><%= life_goal.errors[:title].first %></p>
            </td>
            <td class="field">
              <div class="control">
                <%= f.text_area :what, class: "textarea" %>
              </div>
            </td>
            <td class="field">
              <div class="control">
                <%= f.text_area :why, class: "textarea" %>
              </div>
            </td>
            <td>
              <%= link_to life_goal_path(life_goal), method: :delete, data: { confirm: "Delete Life Goal: #{life_goal.title}?" }, class: "button is-danger is-small is-outlined" do %>
                <span>Delete</span>
                <span class="icon is-small">
                  <i class="fas fa-times"></i>
                </span>
              <% end %>
            </td>
          </tr>
          <% @i += 1 %>
        <% end %>
      <% end %>
    </table>
    <div class="field is-grouped">
      <div class="control">
        <%= submit_tag "Update", class: "button is-primary" %>
      </div>
      <div class="control">
        <%= link_to "Cancel", life_goals_path, class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/life_goals/index.html.erb
<div class="section">

  <div>
    <% if @life_goals.count == 0 %>
      <div class="no-results">
        <%= image_tag "no_results.png", id: "no-results-image" %>
        <div class="has-text-grey">You don't have any life goal!</div>
      </div>
    <% else %>
      <%= form_with model: @life_goals, url: edit_multiple_life_goals_path, local: true, method: :get do %>
        <div class="level">
          <div class="level-left">
            <div class="level-item subtitle">
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              <%= submit_tag "Update goals", class: "button is-small is-outlined is-primary level-item" %>
            </div>
          </div>
        </div>

        <table class="table is-fullwidth">
          <tr>
            <th></th>
            <th>ROLE - I want to be...</th>
            <th>WHAT - It looks/feels like...</th>
            <th>WHY - In order to...</th>
          </tr>
          <% @i = 1%>
          <% @life_goals.each do |life_goal| %>
            <tr> 
              <td>
                #<%= @i %>
                <%= hidden_field_tag "life_goal_ids[]", life_goal.id %>
              </td>
              <td>
                  <%= link_to life_goal.title, life_goal_path(life_goal), class: "modal-button",remote: true %>
              </td>
              <td>
                <%= simple_format(life_goal.what) %>
              </td>
              <td>
                <%= simple_format(life_goal.why) %>
              </td>
            </tr>
            <% @i += 1 %>
          <% end %>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

<div id="modal-window" class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <div id="modal-header"></div>
      <button id="modal-close-button" class="delete is-hidden" aria-label="close"></button>
    </header>
    <section id="modal-content" class="modal-card-body">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <div id="modal-footer"></div>
      <button class="button is-hidden" id="modal-close-button">Close</button>
    </footer>
  </div>
</div>

app/views/life_goals/new.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <h2 class="title">Create a New Life Goal</h2>
    </div>
  </div>
</div>

<%= form_with model: @life_goal, url: life_goals_path, id: "new-life-goal-form", local: true do |f| %>
  <div class="field">
    <label class="label">ROLE - I want to be...</label>
    <div class="control">
      <%= f.text_field :title, class: "input"%>
    </div>
  </div>
  <div class="field">
    <label class="label">WHAT - It looks/feels like</label>
    <div class="control">
      <%= f.text_area :what, class: "textarea"%>
    </div>
  </div>
    <div class="field">
    <label class="label">WHY - In order to...</label>
    <div class="control">
      <%= f.text_area :why, class: "textarea"%>
    </div>
  </div>

  <br/>
  
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Save", class: "button is-primary" %>
    </div>
    <div class="control">
      <%= link_to "Cancel", life_goals_path, class: "button" %>
    </div>
  </div>
<% end %>

app/views/life_goals/new.js.erb
$('#modal-header').html('<%= j render partial: "shared/modal_goal_new_header" %>');
$('#modal-content').html('<%= j render partial: "shared/modal_lifegoal_new" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_goal_new_footer" %>');

app/views/life_goals/show.html.erb
<h2>Title:</h2>
<%= @life_goal.title %>
<h2>What:</h2>
<%= @life_goal.what %>
<h2>Why:</h2>
<%= @life_goal.why %>
<%= link_to "Cancel", life_goals_path, class: "button" %>

app/views/life_goals/show.js.erb
$('#modal-header').html('<%= j render partial: "shared/modal_goal_show_header" %>');
$('#modal-content').html('<%= j render partial: "shared/modal_lifegoal_show" %>');
$('#modal-footer').html('<%= j render partial: "shared/modal_lifegoal_show_footer" %>');

app/views/life_goals/update.js.erb
$('#title-error').html('<%= @life_goal.errors[:title].first %>');
<% if @life_goal.errors[:title].any? %>
  $("#life_goal_title").addClass("is-danger");
  $( "#life_goal_title" ).focus();
<% else %>
  $("#life_goal_title").removeClass("is-danger");
<% end %>